name: Build Windows App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: 'x64'

      - name: Create Python Virtual Environment
        run: |
          python -m venv python_env
          .\python_env\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Python executable
        run: |
          .\python_env\Scripts\activate
          pyinstaller --onefile --noconsole --add-data "models;models" --add-data "config.json;." main.py
          dir dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm install
          npm install electron-builder --save-dev

      - name: Prepare build resources
        run: |
          mkdir resources
          xcopy /E /I python_env resources\python_env
          xcopy /E /I models resources\models
          copy config.json resources\
          copy dist\main.exe resources\

      - name: Build Windows app
        env:
          USE_HARD_LINKS: false
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:css
          npm run build:win

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          retention-days: 5
