name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: read

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup model
        run: |
          chcp 65001
          python download_model.py

      - name: Install NSIS
        shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          $url = "https://sourceforge.net/projects/nsis/files/NSIS%203/3.09/nsis-3.09-setup.exe/download"
          $output = "nsis-setup.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList "/S" -Wait

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "models;models" --add-data "python_env;python_env" --icon=icon.ico main.py

      - name: Build NSIS installer
        run: |
          & 'C:\Program Files (x86)\NSIS\makensis.exe' installer.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDFTranslator-Installer
          path: PDFTranslator_setup.exe
