name: Build Windows App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: 'x64'

      - name: Create Python Virtual Environment
        run: |
          python -m venv python_env
          .\python_env\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Models
        run: |
          .\python_env\Scripts\activate
          python download_model.py
        env:
          HF_ENDPOINT: https://hf-mirror.com
          PYTHONIOENCODING: utf-8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm install
          npm install electron-builder --save-dev

      - name: Prepare build resources
        run: |
          mkdir -p resources\app
          xcopy /E /I /Y python_env resources\app\python_env
          xcopy /E /I /Y models resources\app\models
          xcopy /E /I /Y local_models resources\app\local_models
          copy config.json resources\app\
          copy main.py resources\app\

      - name: Build Windows app
        env:
          USE_HARD_LINKS: false
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:css
          npm run build:win

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          retention-days: 5
