name: Build App

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYTHON_VERSION: "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gettext
          brew link gettext --force
          echo "Checking gettext installation:"
          GETTEXT_PATH=$(brew --prefix gettext)
          echo "Gettext path: $GETTEXT_PATH"
          ls -l "$GETTEXT_PATH/lib/"
          echo "GETTEXT_PATH=$GETTEXT_PATH" >> $GITHUB_ENV
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: "x64"

      - name: Debug Python Info
        run: |
          which python3
          python3 --version
          python3 -c "import sys; print(sys.executable)"
          echo "Current directory: $PWD"
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "Checking dynamic libraries:"
            otool -L $(which python3)
            echo "Gettext location:"
            ls -l "$GETTEXT_PATH/lib/"
          fi
        shell: bash

      - name: Create Python Environment
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            python -m venv python_env
            python_env/Scripts/python -m pip install --upgrade pip
            python_env/Scripts/pip install wheel setuptools
            python_env/Scripts/pip install -r requirements.txt
          else
            export PATH="$GETTEXT_PATH/bin:$PATH"
            export LDFLAGS="-L$GETTEXT_PATH/lib"
            export CPPFLAGS="-I$GETTEXT_PATH/include"
            python3 -m venv python_env
            source python_env/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install wheel setuptools
            python3 -m pip install -r requirements.txt
          fi
        shell: bash

      - name: Verify Python Environment
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            python_env/Scripts/python --version
            python_env/Scripts/pip list
          else
            python_env/bin/python3 --version
            python_env/bin/pip3 list
            echo "Checking Python dynamic libraries:"
            otool -L python_env/bin/python3
          fi
        shell: bash

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          DEBUG: electron-builder
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run build:win
          else
            export PATH="$GETTEXT_PATH/bin:$PATH"
            export LDFLAGS="-L$GETTEXT_PATH/lib"
            export CPPFLAGS="-I$GETTEXT_PATH/include"
            npm run build:mac
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            dist/latest*.yml
          if-no-files-found: warn

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
